[project]
name = "birdie"
version = "0.1.11"
description = "A simple permissive framework to interact with the birdie platform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
]

[tool.uv.workspace]
members = [
    "translation",
]
